# Generated by Django 4.2 on 2024-03-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240314_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('video', 'Video')], default='tutorial', max_length=10),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='pages.page')),
            ],
        ),
    ]
