# Generated by Django 4.2 on 2024-03-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_transfer_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('video', 'Video')], max_length=10),
        ),
    ]
